apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- resources/argocd.namespace.yaml
- resources/argo-managed-cert.yaml
- resources/cloudlockops.appproject.yaml
- resources/argo-ingress.yaml
- resources/argo-backendconfig.yaml
- resources/argo-frontendconfig.yaml

patches:
# - path: patches/git-secrets.secret.yaml
- path: patches/argocd-cmd-params-cm-patch.yaml
- path: patches/argocd.service-patch.yaml
- path: patches/argocd-server-deployment.yaml
- target:
    group: ""
    version: v1
    kind: ConfigMap
    name: argocd-notifications-cm
  path: patches/argocd-notifications-cm.yaml


