apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: checkov
subjects:
- kind: ServiceAccount
  name: checkov
  namespace: checkov
roleRef:
  kind: ClusterRole
  name: checkov-view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: checkov
  namespace: checkov
  annotations:
    checkov.io/skip1: CKV_K8S_22=Checkov requires filesystem write access to dump resource definitions
    checkov.io/skip2: CKV_K8S_38=Service Account is required for read-only API access
    checkov.io/skip3: CKV_K8S_14=Preferring latest rules every run - image pull always
    checkov.io/skip4: CKV_K8S_43=Preferring latest rules every run - image pull always
spec:
  template:
    metadata:
      annotations:
        checkov.io/skip1: CKV_K8S_22=Checkov requires filesystem write access to dump resource definitions
        checkov.io/skip2: CKV_K8S_38=Service Account is required for read-only API access
        checkov.io/skip3: CKV_K8S_14=Preferring latest rules every run - image pull always
        checkov.io/skip4: CKV_K8S_43=Preferring latest rules every run - image pull always
    spec:
      securityContext:
        runAsUser: 12000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      restartPolicy: Never
      serviceAccountName: checkov
      containers:
        - name: checkov
          image: bridgecrew/checkov-k8s:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL