apiVersion: v1
kind: ServiceAccount
metadata:
  name: scan-account 
  namespace: default

  #kubectl annotate serviceaccount scan-account -n default eks.amazonaws.com/role-arn=arn:aws:iam::623045223656:role/eks-nonprod-s3