apiVersion: v1
kind: Secret
metadata:
  name: git-secrets
  namespace: argocd

  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: # Todo
  password: # Todo
  username: # Todo