apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: defectdojo-app-internal
  namespace: defectdojo
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`defectdojo-django.defectdojo.svc.cluster.local`)
      kind: Rule
      services:
        - name: defectdojo-django
          namespace: defectdojo
          port: http
