apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-certificate
spec:
  dnsNames:
    - argocd.cloudlockops.io
  secretName: argocd.cloudlockops.io
  issuerRef:
    name: selfsigned # Use the issuer created previously
    kind: ClusterIssuer