apiVersion: v1
data:
  mapAccounts: |
    []
  mapRoles: |
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::623045223656:role/eks_managed_node1-eks-node-group-20240721235028046600000004"
      "username": "system:node:{{EC2PrivateDNSName}}"
    - "groups":
      - "system:masters"
      "rolearn": "arn:aws:iam::992382399597:role/eks-manage-role-nonprod"
      "username": "eks-manage-role-nonprod"
    - “groups”:
      - “system:masters”
      “rolearn”: “arn:aws:iam::623045223656:role/sec-tooling”
      “username”: “sec-tooling”
    - "groups":
      - "system:masters"
      "rolearn": "arn:aws:iam::623045223656:role/AWSReservedSSO_AdministratorAccess_e3a3b313e3f89f9c"
      "username": "Admin"
    - "groups":
      - "system:masters"
      "rolearn": "arn:aws:iam::623045223656:role/AWSReservedSSO_lambda_iam_8b28109942dcfb1d"
      "username": "lambda_iam_user"
    - "groups":
      - "system:masters"
      "rolearn": "arn:aws:iam::623045223656:role/service-role/lambda-eks"
      "username": “lambda-eks”
  mapUsers: |
    - userarn: arn:aws:iam::623045223656:user/lambda_iam_user
      username: lambda_iam_user
      groups:
      - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2024-07-22T00:00:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1081482"
  uid: 93ec253c-ff08-49f0-9c1a-84e5b7c3b8f7
