apiVersion: v1
kind: Secret
metadata:
  name: traefik-auth-secret
  namespace: traefik
type: kubernetes.io/basic-auth
data:
  username: dXNlcg== # username: user
  password: cGFzc3dvcmQ= # password: password