apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: defectdojo-tls
  namespace: defectdojo
spec:
  secretName: defectdojo-tls
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  commonName: defectdojo.cloudlockops.io
  dnsNames:
  - defectdojo.cloudlockops.io