apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-issuer
spec:
  acme:
    email: chjackson3rd@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudflare:
          email: chjackson3rd@gmail.com
          apiKeySecretRef:
            name: cloudflare-api-key
            key: api-key  # Change here
      selector:
        dnsZones:
        - 'cloudlockops.io'
