apiVersion: v1
kind: Secret
metadata: 
  name: defectdojo
  namespace: defectdojo
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded

type: Opaque
data:
  DD_ADMIN_PASSWORD: YWRtaW4=
  DD_CREDENTIAL_AES_256_KEY: WjBNN3lScmJWY1RZSEw3QU9kVWw5dUR6TjkwOHlpd3FHOEVmOUZnMUduMFpvVm5Od0J3YVJVTE9zcWQwY3hhQ2tvRGlvMnhEZjNsbGpSRnRkbVp2V2RWTGNrVmNSTllZYjV6aldreHpkcWhxUXA2ZkxsV1E3RzhNQkE5bEwzd1k=
  DD_SECRET_KEY: Nm1Bc2FQMjVXemNDSEhac3I3bmpCcHpRWWdLQVM3VFo3SUNCMmF5em1pd1FKcW11UzVaUnBTc0lNeFdPSDN2UnBhTEZlYzhXeTR0cWFZbTdpakxlaDl1a2V1b2tnbFZFN28zbGFNYWZWRGJLdGc4NkhFR20zMDZvWU5jSDJ6TGo=
  METRICS_HTTP_AUTH_PASSWORD: UTdGS0Y5NHlVR3lPSHRGV0NtU245emU0bmxOQTduTW0=
