apiVersion: v1
kind: Secret
metadata:
  name: dojo-secret
type: Opaque
data:
  DOJO_API_KEY: ZGEyMjI3YzRjZGIwYzNmNTA0NGFjNzc4MDA1OTIyMTBjN2Y1ZDMzMA==
  DOJO_URL: aHR0cHM6Ly9kZWZlY3Rkb2pvLnNlY29wcy1iYS53aW4vYXBpL3YyL2ltcG9ydC1zY2FuLw==
