apiVersion: v1
kind: Secret
metadata:
  name: jira-secret
type: Opaque
data:
  JIRA_URL: aHR0cHM6Ly9jbG91ZHJhbmdlcjMuYXRsYXNzaWFuLm5ldA==
  JIRA_USER: Y3JheTk3NDFAb3V0bG9vay5jb20=
  JIRA_API_KEY: QVRBVFQzeEZmR0YwWmFvb19MVThNeG1Gd3ZXYlV3SWRwb2pQR09MYTMyNlBWYWNZV3c4VUlSRGtQNWw1ZkU0SGYwUjZqZFpuVmtMRGpiMHpQcGFvcElrLVVOcC1wMHNhY0pYTkhob2ppVnA2STZvY0dQN0NYQTQ3OExGR3lXX24xaFdOeDVIaVRybS1PMlRDamo1VFRnZnhOdGpNNFpWc19PcXFVQlktX2VwazhFVW1saWlqSTdBPTgxOTJBODYw
